environment                          = "dev"
region                               = "eu-west-1"
project                              = "ikaros-drive"
password_length                      = 6
budget_limits                        = [1, 5, 10, 20]
budgets_subscriber_email_addresses   = ["mark.kedzia@gmail.com", "marek.kedzia.dev@gmail.com"]
mongo_instance_size_name             = "M0"
mongo_cloud_provider_name            = "AWS"
mongo_cluster_ip_whitelist           = ["0.0.0.0"]
mongo_aws_region                     = "EU_WEST_1"
cognito_user_password_minimum_length = 14
files_collection_name                = "files"
free_plan_storage_in_kb              = 1000000
premium_plan_storage_in_kb           = 1000000000
