variable "environment" {}
variable "region" {}
variable "project" {}
variable "password_length" {}
variable "budget_limits" {}
variable "budgets_subscriber_email_addresses" {}
variable "mongo_instance_size_name" {}
variable "mongo_cloud_provider_name" {}
variable "mongo_cluster_ip_whitelist" {}
variable "mongo_aws_region" {}
variable "cognito_user_password_minimum_length" {}
variable "files_collection_name" {}
variable "free_plan_storage_in_kb" {}
variable "premium_plan_storage_in_kb" {}
