#name: 'Terragrunt Dev Apply'
#
#on:
#  push:
#    branches:
#      - main
#
#env:
#  tf_version: 'latest'
#  tg_version: 'latest'
#  tf_working_dir: './accounts'
#  AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
#  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
#  MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.DEV_MONGO_PUBLIC_KEY }}
#  MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.DEV_MONGO_PRIVATE_KEY }}
#  TERRAGRUNT_CONFIG: '--terragrunt-config terragrunt-dev.hcl'
#
#jobs:
#  terragrunt:
#    name: 'Terragrunt Dev Apply'
#    runs-on: ubuntu-latest
#    steps:
#      - name: 'Checkout'
#        uses: actions/checkout@master
#      - name: 'Init'
#        uses: the-commons-project/terragrunt-github-actions@master
#        with:
#          tf_actions_version: ${{ env.tf_version }}
#          tg_actions_version: ${{ env.tg_version }}
#          tf_actions_subcommand: 'init'
#          tf_actions_working_dir: ${{ env.tf_working_dir }}
#          tf_actions_comment: false
#          args: ${{ env.TERRAGRUNT_CONFIG }}
#      - name: 'Apply'
#        uses: the-commons-project/terragrunt-github-actions@master
#        with:
#          tf_actions_version: ${{ env.tf_version }}
#          tg_actions_version: ${{ env.tg_version }}
#          tf_actions_subcommand: 'apply'
#          tf_actions_working_dir: ${{ env.tf_working_dir }}
#          tf_actions_comment: false
#          args: ${{ env.TERRAGRUNT_CONFIG }}
