#name: 'Terragrunt Dev Plan'
#on:
#  pull_request:
#
#env:
#  tf_version: 'latest'
#  tg_version: 'latest'
#  tf_working_dir: './accounts'
#  AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
#  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
#  MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.DEV_MONGO_PUBLIC_KEY }}
#  MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.DEV_MONGO_PRIVATE_KEY }}
#  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  TERRAGRUNT_CONFIG: '--terragrunt-config terragrunt-dev.hcl'
#jobs:
#  terragrunt:
#    name: 'Terragrunt Dev Plan'
#    runs-on: ubuntu-latest
#    steps:
#      - name: 'Checkout'
#        uses: actions/checkout@master
#      - name: 'Terragrunt Format'
#        uses: the-commons-project/terragrunt-github-actions@master
#        with:
#          tf_actions_version: ${{ env.tf_version }}
#          tg_actions_version: ${{ env.tg_version }}
#          tf_actions_binary: 'terraform'
#          tf_actions_subcommand: 'fmt'
#          tf_actions_working_dir: ${{ env.tf_working_dir }}
#          tf_actions_comment: true
#      - name: 'Terragrunt Dev Init'
#        uses: the-commons-project/terragrunt-github-actions@master
#        with:
#          tf_actions_version: ${{ env.tf_version }}
#          tg_actions_version: ${{ env.tg_version }}
#          tf_actions_subcommand: 'init'
#          tf_actions_working_dir: ${{ env.tf_working_dir }}
#          tf_actions_comment: true
#          args: '--terragrunt-non-interactive ${{ env.TERRAGRUNT_CONFIG }}'
#      - name: 'Terragrunt Dev Validate'
#        uses: the-commons-project/terragrunt-github-actions@master
#        with:
#          tf_actions_version: ${{ env.tf_version }}
#          tg_actions_version: ${{ env.tg_version }}
#          tf_actions_binary: 'terraform'
#          tf_actions_subcommand: 'validate'
#          tf_actions_working_dir: ${{ env.tf_working_dir }}
#          tf_actions_comment: true
#      - name: 'Terragrunt Dev Plan'
#        uses: the-commons-project/terragrunt-github-actions@master
#        with:
#          tf_actions_version: ${{ env.tf_version }}
#          tg_actions_version: ${{ env.tg_version }}
#          tf_actions_subcommand: 'plan'
#          tf_actions_working_dir: ${{ env.tf_working_dir }}
#          tf_actions_comment: true
#          args: ${{ env.TERRAGRUNT_CONFIG }}
